### ISSUE TITLE
Fix failing specs

### ISSUE THREAD

**Issue by perlun** [mizunorb/mizuno#2]
There seems to be a number of specs that are failing. We should go through them and fix them all.

**Comment by perlun** [comment]
This is the full list:

```
Failures:

  1) Mizuno::Client makes http requests to google
     Failure/Error: called.should be_true
       expected false to respond to `true?` or perhaps you meant `be true` or `be_truthy`
     # ./spec/client_spec.rb:27:in `block in (root)'

  2) Mizuno::Client makes multiple requests
     Failure/Error: queue.size.should == 2

       expected: 2
            got: 0 (using ==)
     # ./spec/client_spec.rb:42:in `block in (root)'

  3) Mizuno::Client has a root exchange
     Failure/Error: called.should be_true
       expected false to respond to `true?` or perhaps you meant `be true` or `be_truthy`
     # ./spec/client_spec.rb:69:in `block in (root)'

  4) daemonization reloads on SIGHUP only if app has been updated
     Failure/Error: expect(third).to be > first

       expected: > 0
            got:   0
     # ./spec/daemonization_spec.rb:158:in `block in (root)'

  5) daemonization reloads when a trigger file is touched
     Failure/Error: expect(third).to be > first

       expected: > 0
            got:   0
     # ./spec/daemonization_spec.rb:178:in `block in (root)'

  6) daemonization reloads from the command line
     Failure/Error: expect(third).to be > first

       expected: > 0
            got:   0
     # ./spec/daemonization_spec.rb:198:in `block in (root)'

  7) daemonization handles ssl requests FIXED
     Expected pending 'No reason given' to fail. No Error was raised.

  8) daemonization handles spdy requests FIXED
     Expected pending 'No reason given' to fail. No Error was raised.

  9) daemonization writes server logs to a file FIXED
     Expected pending 'No reason given' to fail. No Error was raised.

  10) daemonization allows for rotation of server logs FIXED
      Expected pending 'No reason given' to fail. No Error was raised.

  11) daemonization switches to a different group FIXED
      Expected pending 'To test uid/gid switching, run tests as root.' to fail. No Error was raised.

  12) daemonization switches to a different user FIXED
      Expected pending 'To test uid/gid switching, run tests as root.' to fail. No Error was raised.

  13) rails support sets the environment for rails FIXED
      Expected pending 'No reason given' to fail. No Error was raised.

  14) rails support runs in development mode FIXED
      Expected pending 'No reason given' to fail. No Error was raised.

  15) rails support runs in production mode FIXED
      Expected pending 'No reason given' to fail. No Error was raised.

  16) rails support serves up static assets in production mode FIXED
      Expected pending 'No reason given' to fail. No Error was raised.

  17) Mizuno::Server https
      Failure/Error: http.verify_mode = OpenSSL::SSL::VERIFY_NONE

      NameError:
        uninitialized constant OpenSSL
      # ./spec/server_spec.rb:193:in `block in (root)'

  18) Mizuno::Server http rack headers
      Failure/Error: content['rack.version'].should eq [1, 2]

        expected: [1, 2]
             got: [1, 3]

        (compared using ==)
      # ./spec/server_spec.rb:38:in `block in (root)'

  19) Mizuno::Server http rack.java.servlet
      Failure/Error: content['rack.java.servlet'].should be_true
        expected true to respond to `true?` or perhaps you meant `be true` or `be_truthy`
      # ./spec/server_spec.rb:70:in `block in (root)'
```
